# Pokes Plugin by TechieCrow
#
# Prefix = plugin prefix.
# Poker Message = The message the poker receives.
# Poked Message = The message the poked receives.
# Poke Sound = The sound the poked hears. (https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html)
# CoolDown = the cooldown time in seconds.
# %poked_name% = The poked players name.
# %poker_name% = The poker players name.
# %count% = The number of pokes the player has received.
# If you have problems using SSL for the database connection please change it to false
#

Prefix: '&a[&bPokes&a]&f '

Poker Message: '&a&l&oYou have poked: &b&l&o%poked_name%'

Poked Message: '&a&l&oYou were poked by: &b&l&o%poker_name%'

Count Message: '%poked_name% &a&l&oHas been poked &b&l&o%count% &a&l&otimes'

Poke Sound: 'ENTITY_PIG_AMBIENT'

CoolDown: 30

Enable Database: false

SQL Host: localhost

SQL Port: 3306

SQL Username: username

SQL Password: Password

SQL Database: Database

SQL Use SSL: false